import { useParams } from 'react-router-dom'
import SeverityBadge from '../components/SeverityBadge'
import { useApi } from '../hooks/useApi'

export default function ReportView() {
  const { id } = useParams()
  const { data, loading } = useApi(`/api/reports/${id}?fmt=json`)
  const { data: mdData } = useApi(`/api/reports/${id}?fmt=markdown`)

  if (loading) return <p className="text-[#a3a3a3]">Loading...</p>
  if (!data || data.error) return <p className="text-red-400">Report not found.</p>

  const r = data

  function copyMarkdown() {
    if (mdData?.content) {
      navigator.clipboard.writeText(mdData.content)
    }
  }

  function copyText() {
    fetch(`/api/reports/${id}?fmt=text`)
      .then((res) => res.json())
      .then((d) => navigator.clipboard.writeText(d.content))
  }

  function downloadJson() {
    const blob = new Blob([JSON.stringify(r, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${id}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div>
      <div className="flex items-center gap-4 mb-6">
        <SeverityBadge severity={r.severity} />
        <h1 className="text-xl font-bold">{r.title || r.report_id}</h1>
      </div>

      {/* Actions */}
      <div className="flex gap-3 mb-6">
        <button onClick={copyMarkdown} className="border border-[#2a2a2a] bg-[#1a1a1a] text-[#e5e5e5] px-3 py-1.5 text-sm cursor-pointer hover:bg-[#2a2a2a]">
          Copy Markdown
        </button>
        <button onClick={copyText} className="border border-[#2a2a2a] bg-[#1a1a1a] text-[#e5e5e5] px-3 py-1.5 text-sm cursor-pointer hover:bg-[#2a2a2a]">
          Copy Plain Text
        </button>
        <button onClick={downloadJson} className="border border-[#2a2a2a] bg-[#1a1a1a] text-[#e5e5e5] px-3 py-1.5 text-sm cursor-pointer hover:bg-[#2a2a2a]">
          Download JSON
        </button>
      </div>

      {/* Summary */}
      <Section title="SUMMARY">
        <p className="text-sm">{r.summary}</p>
      </Section>

      {/* Affected Entities */}
      {r.affected_entities && (
        <Section title="AFFECTED ENTITIES">
          <div className="grid grid-cols-2 gap-2">
            {Object.entries(r.affected_entities).map(([k, v]) => (
              <div key={k} className="text-sm">
                <span className="text-[#6b7280]">{k}: </span>
                <span className="mono">{String(v)}</span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Evidence */}
      <Section title="EVIDENCE">
        <pre className="mono text-xs bg-[#111111] p-4 overflow-x-auto">
          {JSON.stringify(r.evidence, null, 2)}
        </pre>
      </Section>

      {/* Chain References */}
      {r.chain_references?.length > 0 && (
        <Section title="CHAIN REFERENCES">
          {r.chain_references.map((ref, i) => (
            <div key={i} className="text-sm mb-1">
              <span className="text-[#6b7280]">{ref.type}: </span>
              <span className="mono">{ref.hash || ref.number}</span>
              {ref.explorer_url && (
                <a
                  href={ref.explorer_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#f59e0b] ml-2 text-xs hover:underline"
                >
                  View on Explorer
                </a>
              )}
            </div>
          ))}
        </Section>
      )}

      {/* Investigation */}
      {r.recommended_investigation?.length > 0 && (
        <Section title="RECOMMENDED INVESTIGATION">
          <ol className="list-decimal list-inside space-y-1">
            {r.recommended_investigation.map((step, i) => (
              <li key={i} className="text-sm">{step}</li>
            ))}
          </ol>
        </Section>
      )}

      {/* Plain English */}
      {r.plain_english && (
        <Section title="PLAIN ENGLISH">
          <p className="text-sm">{r.plain_english}</p>
        </Section>
      )}

      <div className="text-xs text-[#6b7280] mt-8 border-t border-[#2a2a2a] pt-4">
        Generated by MONOLITH v{r.version || '0.1.0'} — EVE Frontier Blockchain Integrity Monitor
      </div>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div className="border border-[#2a2a2a] p-4 mb-4">
      <h2 className="text-xs font-bold text-[#a3a3a3] uppercase tracking-wider mb-3">{title}</h2>
      {children}
    </div>
  )
}
