"""Sui blockchain read-only queries for Warden threat verification.

Provides direct chain queries to verify hypotheses generated by the Warden
system. All queries are read-only — Warden never writes to chain.
"""

import logging

import httpx

logger = logging.getLogger(__name__)

# Default timeout for Sui testnet (can be slow)
SUI_TIMEOUT = 15.0


async def get_object_state(
    rpc_url: str,
    object_id: str,
    client: httpx.AsyncClient | None = None,
) -> dict | None:
    """Fetch current on-chain state of a Sui object.

    Returns parsed object data or None on failure.
    """
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "sui_getObject",
        "params": [
            object_id,
            {"showContent": True, "showOwner": True, "showType": True},
        ],
    }
    return await _rpc_call(rpc_url, payload, client)


async def get_object_events(
    rpc_url: str,
    object_id: str,
    limit: int = 50,
    client: httpx.AsyncClient | None = None,
) -> list[dict]:
    """Fetch recent events referencing an object via transaction lookup."""
    # First get recent transactions for this object
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "suix_queryEvents",
        "params": [
            {"MoveEventField": {"path": "/object_id", "value": object_id}},
            None,
            limit,
            True,
        ],
    }
    result = await _rpc_call(rpc_url, payload, client)
    if result and isinstance(result.get("data"), list):
        return result["data"]
    return []


async def get_latest_checkpoint(
    rpc_url: str,
    client: httpx.AsyncClient | None = None,
) -> int:
    """Get the latest checkpoint sequence number — used for health/freshness."""
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "suix_getLatestCheckpointSequenceNumber",
        "params": [],
    }
    result = await _rpc_call(rpc_url, payload, client)
    if result is not None:
        try:
            return int(result)
        except (TypeError, ValueError):
            pass
    return 0


async def verify_object_exists(
    rpc_url: str,
    object_id: str,
    client: httpx.AsyncClient | None = None,
) -> bool:
    """Check if a Sui object exists on chain. Returns False for deleted/non-existent."""
    result = await get_object_state(rpc_url, object_id, client)
    if result is None:
        return False
    # sui_getObject returns error.code = "notExists" for missing objects
    return not (isinstance(result, dict) and "error" in result)


async def get_dynamic_fields(
    rpc_url: str,
    parent_id: str,
    limit: int = 50,
    client: httpx.AsyncClient | None = None,
) -> list[dict]:
    """Fetch dynamic fields of a Sui object (e.g. Table entries)."""
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "suix_getDynamicFields",
        "params": [parent_id, None, limit],
    }
    result = await _rpc_call(rpc_url, payload, client)
    if result and isinstance(result.get("data"), list):
        return result["data"]
    return []


async def _rpc_call(
    rpc_url: str,
    payload: dict,
    client: httpx.AsyncClient | None = None,
) -> dict | None:
    """Execute a Sui JSON-RPC call. Returns result field or None on error."""
    try:
        if client:
            resp = await client.post(rpc_url, json=payload, timeout=SUI_TIMEOUT)
        else:
            async with httpx.AsyncClient() as c:
                resp = await c.post(rpc_url, json=payload, timeout=SUI_TIMEOUT)

        if resp.status_code != 200:
            logger.warning("Sui RPC HTTP %d: %s", resp.status_code, resp.text[:200])
            return None

        data = resp.json()
        if "error" in data:
            logger.debug("Sui RPC error: %s", data["error"])
            return data  # Caller may want to inspect error
        return data.get("result")
    except (httpx.HTTPError, OSError) as e:
        logger.warning("Sui RPC call failed: %s", e)
        return None
