"""Report formatter — renders bug reports to markdown, JSON, and plain text.

Produces the exact format specified in the Build Bible.
"""

import json
from datetime import UTC, datetime


def format_markdown(report: dict) -> str:
    """Render a report as formatted markdown."""
    evidence = _parse_json(report.get("evidence_json", "{}"))
    chain_refs = _parse_json(report.get("chain_references", "[]"))
    reproduction = _parse_json(report.get("reproduction_context", "{}"))
    investigation = _parse_json(report.get("recommended_investigation", "[]"))

    generated_at = _format_timestamp(report.get("generated_at", 0))

    lines = [
        "# MONOLITH BUG REPORT",
        "",
        f"**Report ID:** {report['report_id']}",
        f"**Generated:** {generated_at}",
        f"**Severity:** {report['severity']}",
        f"**Category:** {report['category']}",
        f"**Detector:** {report.get('anomaly_id', '')} / {reproduction.get('rule_id', '')}",
        "**Status:** UNVERIFIED",
        "",
        "---",
        "",
        "## Summary",
        "",
        report.get("summary", "No summary available."),
        "",
        "---",
        "",
        "## Affected Entities",
        "",
    ]

    affected = _parse_json(json.dumps(report.get("affected_entities", {})))
    if isinstance(affected, str):
        affected = _parse_json(affected)
    for key, val in (affected if isinstance(affected, dict) else {}).items():
        lines.append(f"- **{key}:** `{val}`")

    lines.extend(
        [
            "",
            "---",
            "",
            "## Evidence",
            "",
            "```json",
            json.dumps(evidence, indent=2),
            "```",
            "",
            "---",
            "",
            "## Chain References",
            "",
        ]
    )

    if chain_refs and isinstance(chain_refs, list):
        for ref in chain_refs:
            label = ref.get("label", ref.get("type", "reference"))
            url = ref.get("explorer_url", "")
            hash_val = ref.get("hash", ref.get("number", ""))
            lines.append(f"- **{label}:** `{hash_val}` — [View on Explorer]({url})")
    else:
        lines.append("No chain references available.")

    lines.extend(
        [
            "",
            "---",
            "",
            "## Reproduction Context",
            "",
            "```json",
            json.dumps(reproduction, indent=2),
            "```",
            "",
            "---",
            "",
            "## Recommended Investigation",
            "",
        ]
    )

    if isinstance(investigation, list):
        for i, step in enumerate(investigation, 1):
            lines.append(f"{i}. {step}")
    else:
        lines.append("No specific investigation steps available.")

    # Plain English section
    plain = report.get("plain_english", "")
    if plain:
        lines.extend(
            [
                "",
                "---",
                "",
                "## Plain English",
                "",
                plain,
            ]
        )

    lines.extend(
        [
            "",
            "---",
            "",
            "*Generated by MONOLITH v0.2.0 — EVE Frontier Blockchain Integrity Monitor*",
        ]
    )

    return "\n".join(lines)


def format_json(report: dict) -> dict:
    """Render a report as a machine-readable JSON dict."""
    return {
        "report_id": report["report_id"],
        "anomaly_id": report.get("anomaly_id", ""),
        "title": report.get("title", ""),
        "severity": report["severity"],
        "category": report["category"],
        "summary": report.get("summary", ""),
        "affected_entities": report.get("affected_entities", {}),
        "evidence": _parse_json(report.get("evidence_json", "{}")),
        "chain_references": _parse_json(report.get("chain_references", "[]")),
        "reproduction_context": _parse_json(report.get("reproduction_context", "{}")),
        "recommended_investigation": _parse_json(report.get("recommended_investigation", "[]")),
        "plain_english": report.get("plain_english", ""),
        "generated_at": report.get("generated_at", 0),
        "generated_at_iso": _format_timestamp(report.get("generated_at", 0)),
        "version": "0.2.0",
    }


def format_text(report: dict) -> str:
    """Render a report as plain text (for Discord/forum posting)."""
    evidence = _parse_json(report.get("evidence_json", "{}"))
    investigation = _parse_json(report.get("recommended_investigation", "[]"))
    generated_at = _format_timestamp(report.get("generated_at", 0))

    lines = [
        "MONOLITH BUG REPORT",
        "=" * 50,
        f"Report ID:  {report['report_id']}",
        f"Generated:  {generated_at}",
        f"Severity:   {report['severity']}",
        f"Category:   {report['category']}",
        "",
        "SUMMARY",
        "-" * 50,
        report.get("summary", "No summary."),
        "",
        "EVIDENCE",
        "-" * 50,
        json.dumps(evidence, indent=2),
        "",
    ]

    plain = report.get("plain_english", "")
    if plain:
        lines.extend(
            [
                "PLAIN ENGLISH",
                "-" * 50,
                plain,
                "",
            ]
        )

    if isinstance(investigation, list) and investigation:
        lines.append("RECOMMENDED INVESTIGATION")
        lines.append("-" * 50)
        for i, step in enumerate(investigation, 1):
            lines.append(f"  {i}. {step}")
        lines.append("")

    lines.extend(
        [
            "=" * 50,
            "Generated by MONOLITH v0.2.0",
            "EVE Frontier Blockchain Integrity Monitor",
        ]
    )

    return "\n".join(lines)


def _parse_json(val) -> dict | list:
    """Safely parse a JSON string, returning empty dict on failure."""
    if isinstance(val, (dict, list)):
        return val
    try:
        return json.loads(val)
    except (json.JSONDecodeError, TypeError):
        return {}


def _format_timestamp(ts: int) -> str:
    """Format a Unix timestamp as ISO 8601."""
    if not ts:
        return "unknown"
    return datetime.fromtimestamp(ts, tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
